@startuml
title House Control System

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(User, "Пользователь", "Пользователь/Администратор системы контроля умного дома")
System(HouseControlSystem, "Система контроля Умного дома", "Система управления системами умного дома")

System_Ext(HouseControlHub, "Хаб управления умным домом", "Хаб управления умным домом, к которому подключены все системы умного дома")
System_Ext(HeatSystem, "Система отопления", "Система отопления на объекте, подключенная к хабу")
System_Ext(WaterSystem, "Система водоснабжения", "Система водоснабжения на объекте, подключенная к хабу")
System_Ext(TemperatureSensor1, "Датчик температуры", "Датчик температуры, связанный с хабом и установленный на объекте")
System_Ext(TemperatureSensor2, "Датчик температуры", "Датчик температуры, связанный с хабом и установленный на объекте")
System_Ext(WaterSensor1, "Датчик протечек", "Датчик протечек, связанный с хабом и установленный на объекте")
System_Ext(WaterSensor2, "Датчик протечек", "Датчик протечек, связанный с хабом и установленный на объекте")
System_Ext(NotificationSystemPush, "Система push уведомлений", "Система, через которую направляются все push уведомления")
System_Ext(NotificationSystemEmail, "Система email уведомлений", "Система, через которую направляются все email уведомления")
System_Ext(NotificationSystemSms, "Система sms уведомлений", "Система, через которую направляются все sms уведомления")

Container_Boundary(HouseControlSystem, "Система контроля Умного дома") {
  Container(WebApp, "Web Application", "Java, Spring", "Взаимодействие с пользователями и хабами умных домов")
  Container(MobileApp, "Mobile Application", "Kotlin, Swift", "Регистрация/удаление аккаунта,подключение хабов управления умного дома,получение актуальной информации о системах умного дома")
  Container(DatabaseSQL, "Database SQL", "PostgreSQL", "Хранение данных о пользователях, системах, состояниях")
  Container(DatabaseNoSQL, "Database NoSQL", "Mongo", "Хранение показателей датчиков")
  Container(CacheDatabase, "Cache", "Redis", "Хранение агрегатов состояний")
}


Rel(User, HouseControlSystem, "Получение информации\nзаведение сценариев для систем умного дома")
Rel(HouseControlHub, HouseControlSystem, "Передача актуального состояния систем")
Rel(HouseControlSystem, HouseControlHub, "Передача управляющих воздействий")
Rel(HouseControlHub, HeatSystem, "Передача управляющих воздействий")
Rel(HouseControlHub, WaterSystem, "Передача управляющих воздействий")
Rel(TemperatureSensor1, HouseControlHub, "Передача актуального состояния системы")
Rel(TemperatureSensor2, HouseControlHub, "Передача актуального состояния системы")
Rel(WaterSensor1, HouseControlHub, "Передача актуального состояния системы")
Rel(WaterSensor2, HouseControlHub, "Передача актуального состояния системы")
Rel(HouseControlSystem, NotificationSystemPush, "Передача push уведомлений на отправку")
Rel(HouseControlSystem, NotificationSystemEmail, "Передача email уведомлений на отправку")
Rel(HouseControlSystem, NotificationSystemSms, "Передача sms уведомлений на отправку")
Rel(NotificationSystemPush, User, "Передача push уведомлений")
Rel(NotificationSystemEmail, User, "Передача email уведомлений")
Rel(NotificationSystemSms, User, "Передача sms уведомлений")

@enduml