@startuml
title Monolith C4 Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(User, "Пользователь", "Пользователь/Администратор системы отопления")
System(MonolithSystem, "Монолитное приложение", "Система управления системами отопления и предоставления данных пользователю")

System_Ext(HeatSystem, "Система отопления", "Система отопления на объекте")
System_Ext(TemperatureSensor, "Датчик температуры", "Датчик температуры, связанный с приложением и установленный на объекте")

Rel(User, MonolithSystem, "Вкл/Выкл Систему отопления\nУказание целевого уровня температуры\nЗапрос текущих показаний")
Rel(MonolithSystem,HeatSystem,"Получение данных о состоянии\nУправляющее воздействие на систему")
Rel(TemperatureSensor,MonolithSystem,"Передача показателей с датчиков,\n установленных на объекте")

@enduml